services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: health_db

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:0000@db:5432/health_db
      SECURITY_KEY: a693441bf2ffcd8e3cbc0cf053ba3396e60d3bc5cb2ca6b0e22c57f51d7baf77
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    depends_on:
      - db
    command:
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"