"""add model_registry and model_version table

Revision ID: 0cdee26f8097
Revises: 63a32fcfca98
Create Date: 2026-05-11 16:51:44.140414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cdee26f8097'
down_revision: Union[str, Sequence[str], None] = '63a32fcfca98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_tag', sa.String(), nullable=True),
    sa.Column('stage', sa.Enum('DEV', 'STAGING', 'PRODUCTION', 'ARCHIVED', name='modelstage'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('feature_set', sa.JSON(), nullable=True),
    sa.Column('preprocessing_config', sa.JSON(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('train_ratio', sa.Float(), nullable=True),
    sa.Column('val_ratio', sa.Float(), nullable=True),
    sa.Column('test_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('algorithm', sa.String(), nullable=True),
    sa.Column('stage', sa.Enum('DEV', 'STAGING', 'PRODUCTION', 'ARCHIVED', name='modelstage'), nullable=True),
    sa.Column('hyperparameter', sa.JSON(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_registry')
    op.drop_table('model_version')
    # ### end Alembic commands ###
