"""update alert table column settings

Revision ID: 4556d5b8bcc1
Revises: 81ce4e6b84bc
Create Date: 2026-04-05 14:35:47.159080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4556d5b8bcc1'
down_revision: Union[str, Sequence[str], None] = '81ce4e6b84bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('alerts', 'recording_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('alerts', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('alerts', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('alerts', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('alerts', 'recording_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('alerts', 'created_at')
    # ### end Alembic commands ###
