"""update sensor add created_at column

Revision ID: 5846b9bfbb6e
Revises: efc683e4bc1f
Create Date: 2026-04-04 21:51:45.751216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5846b9bfbb6e'
down_revision: Union[str, Sequence[str], None] = 'efc683e4bc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
