"""update sensor add created_at column

Revision ID: 81ce4e6b84bc
Revises: 5846b9bfbb6e
Create Date: 2026-04-04 23:39:19.486112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ce4e6b84bc'
down_revision: Union[str, Sequence[str], None] = '5846b9bfbb6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_recordings', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_recordings', 'created_at')
    # ### end Alembic commands ###
