"""update sex options and other attribute to nullable

Revision ID: 9f50ea4c3cb9
Revises: e814ec188503
Create Date: 2026-04-04 15:01:05.381542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f50ea4c3cb9'
down_revision: Union[str, Sequence[str], None] = 'e814ec188503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TYPE sexenum AS ENUM ('male', 'female', 'intersex')")
    
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('male', 'female', 'intersex', name='sexenum'),
               postgresql_using="sex::sexenum",
               existing_nullable=True)
    op.alter_column('users', 'user_type',
               existing_type=postgresql.ENUM('PATIENT', 'CAREGIVER', 'ADMIN', name='usertypeenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_type',
               existing_type=postgresql.ENUM('PATIENT', 'CAREGIVER', 'ADMIN', name='usertypeenum'),
               nullable=False)
    op.alter_column('users', 'sex',
               existing_type=sa.Enum('male', 'female', 'intersex', name='sexenum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.execute("DROP TYPE sexenum")  # 回滚时删掉这个类型
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###
