"""add device serail_number column unique

Revision ID: de5225268f88
Revises: 1c7a0d336104
Create Date: 2026-04-04 19:10:24.890030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5225268f88'
down_revision: Union[str, Sequence[str], None] = '1c7a0d336104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('serial_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'devices', ['serial_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_column('devices', 'serial_number')
    # ### end Alembic commands ###
