"""update sensor recording columns

Revision ID: efc683e4bc1f
Revises: de5225268f88
Create Date: 2026-04-04 21:43:28.046100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc683e4bc1f'
down_revision: Union[str, Sequence[str], None] = 'de5225268f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor_recordings', 'device_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_sensor_recordings_device_id'), 'sensor_recordings', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_recordings_user_id'), 'sensor_recordings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_recordings_user_id'), table_name='sensor_recordings')
    op.drop_index(op.f('ix_sensor_recordings_device_id'), table_name='sensor_recordings')
    op.alter_column('sensor_recordings', 'device_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
