name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production


    services:
      db:
        image: postgres:16
        env:
          POSTGRES_USER: ${{vars.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{vars.TEST_POSTGRES_DB}}
        ports:
          - 5432:5432 # host port: container port container port — expose db to the runner so pytest can connect via localhost

        # check if PostgreSQL is ready to accept connections, r
        # un the health check every 10 seconds
        # each check times out after 5 seconds,
        # fail the container after 5 consecutive failures
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5



    steps:
      - uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r apps/backend/requirements.txt

      - name: Run tests
        working-directory: apps/backend
        env:
          DATABASE_URL: ${{secrets.TEST_DATABASE_URL}}
          SECURITY_KEY: ${{secrets.TEST_SECURITY_KEY}}
          ALGORITHM: ${{vars.ALGORITHM}}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{vars.ACCESS_TOKEN_EXPIRE_MINUTES}}
        run: pytest tests/ -v

      - name: Deploy
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECURITY_KEY: ${{ secrets.SECURITY_KEY }}
          ALGORITHM: ${{ vars.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ vars.ACCESS_TOKEN_EXPIRE_MINUTES }}
        run: docker compose up -d

      - name: Build Docker image
        run: docker build apps/backend/